services:
  - type: web
    name: inventory-management-app
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: inventory-management-app
          property: host
      - key: GOOGLE_GEMINI_API_KEY
        sync: false # Set this manually in Render dashboard

databases:
  - name: inventory-db
    region: oregon
    plan: starter
    databaseName: inventory_management
    user: inventory_user 